spring:
  application:
    name: Food_Saver

  datasource:
    url: jdbc:mysql://localhost:3306/food_saver
    username: root
    password: Bankai

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  spring:
    security:
      oauth2:
        client:
          registration:
            google:
              client-id: ${GOOGLE_CLIENT_ID}
              client-secret: ${GOOGLE_CLIENT_SECRET}

